In [ ]:
"http://energiaeambiente.org.br/qualidadedoar"
"https://op.europa.eu/webpub/eca/special-reports/air-quality-23-2018/pt/"
"https://cetesb.sp.gov.br/ar/padroes-de-qualidade-do-ar/"

In [3]:
####### LÓGICA PROGRAMA #######
import matplotlib.pyplot
import pandas as pd

def read_dataset(path, encoding_type='ISO-8859-1'):
    return pd.read_csv(path, encoding=encoding_type)

def dataset_visualize_items_specific_columns(dataset, column_name):
    return dataset[column_name].value_counts()

def filter_dataset_by_column(dataset, column_name, item_column):
    return dataset.loc[dataset[column_name] == item_column]

def obtain_mean_group_of_numerical_column_by_day(dataset, column_name):
    return dataset.groupby(column_name).mean()

def obtain_mean_group_of_numerical_column_by_month(dataset, column_name, result):
    dataset[column_name] = pd.to_datetime(dataset[column_name])
    return dataset.groupby(dataset[column_name].dt .month) [result]. mean()

def obtain_mean_group_of_numerical_column_by_year(dataset, column_name):
    return dataset.groupby(column_name).mean()

def return_year_dataset(dataset, column_name):
    dataset[column_name] = pd.to_datetime(dataset[column_name])
    return int(dataset[column_name].dt .year.head(1))

In [16]:
path = '/Users/mtcd/Library/Mobile Documents/com~apple~CloudDocs/@Pessoal/@Evernote/Estudos/@programming/p.qualidade_ar_work/dataset/DF/2015DF.csv'
encoding = 'ISO-8859-1'

dataset_recovered = read_dataset(path, encoding)

# VISUALIZAR O DATASET
#dataset_recovered

# VISUALIZAR COLUNAS EXIXTENTES
#dataset_recovered.columns

# VISUALIZAR POLUENTES COLETADOS
#dataset_visualize_items_specific_columns(dataset_recovered, 'Poluente')

# VISUALIZAR ESTAÇÕES EXISTENTES
dataset_visualize_items_specific_columns(dataset_recovered, 'Estacao')


# FILTRAR OS DADOS POR COLUNA
filter_dataset_by_column(dataset_recovered, 'Estacao', 'Rodoviária do Plano Piloto')

#ds_cubatao_poluente = filter_dataset_by_column(ds_cubatao, 'Poluente', 'O3')

#ds_cubatao_poluente_media_dia = obtain_mean_group_of_numerical_column_by_day(ds_cubatao_poluente, 'Data')

#ds_cubatao_mp10_media_dia
#ds_cubatao_poluente
#ds_cubatao

#obtain_mean_group_of_numerical_column_by_month(ds_cubatao_poluente, 'Data', 'Valor')

#obtain_mean_group_of_numerical_column_by_year(ds_cubatao_poluente, "Poluente")
#print(ds_cubatao_poluente)

#dataset_visualize_items_specific_columns(ds_cubatao, 'Poluente')
#return_year_dataset(ds_cubatao_poluente, 'Data')
#ds_cubatao


#dataset_recovered.groupby()

,Data,Hora,Estacao,Codigo,Poluente,Valor,Unidade,Tipo
0,2015-01-06,01:00,Rodoviária do Plano Piloto,DF03,PTS,128.70,ug/m3,manual
1,2015-01-08,01:00,Rodoviária do Plano Piloto,DF03,PTS,56.67,ug/m3,manual
2,2015-01-10,01:00,Rodoviária do Plano Piloto,DF03,PTS,128.33,ug/m3,manual
3,2015-01-13,01:00,Rodoviária do Plano Piloto,DF03,PTS,108.55,ug/m3,manual
4,2015-01-15,01:00,Rodoviária do Plano Piloto,DF03,PTS,123.06,ug/m3,manual
...,...,...,...,...,...,...,...,...
314,2015-11-07,01:00,Rodoviária do Plano Piloto,DF03,FMC,5.81,ug/m3,manual
315,2015-11-13,01:00,Rodoviária do Plano Piloto,DF03,FMC,10.39,ug/m3,manual
316,2015-11-20,01:00,Rodoviária do Plano Piloto,DF03,FMC,3.74,ug/m3,manual
317,2015-11-26,01:00,Rodoviária do Plano Piloto,DF03,FMC,25.33,ug/m3,manual
318,2015-12-05,01:00,Rodoviária do Plano Piloto,DF03,FMC,12.08,ug/m3,manual

In [5]:

files = [
    '/Users/mtcd/Library/Mobile Documents/com~apple~CloudDocs/@Pessoal/@Evernote/Estudos/@programming/p.qualidade_ar_work/dataset/2019SP01.csv',
    '/Users/mtcd/Library/Mobile Documents/com~apple~CloudDocs/@Pessoal/@Evernote/Estudos/@programming/p.qualidade_ar_work/dataset/SP202001.csv',
]

stations = [
    'Cubatão - Centro',
    'Itaim Paulista'
]

pollutants = [
    'MP10',
    '03[]'
]

for file in files:
    path = file
    dataset_recovered = read_dataset(path)
    year_dataset = return_year_dataset(dataset_recovered, 'Data')
    #print(year_dataset)

    for station in stations:
        datas = []
        #print(station)
        for pollutant in pollutants:
            #print(pollutant)
            ds_filtered = filter_dataset_by_column(dataset_recovered, 'Estacao', station)
            ds_filtered = filter_dataset_by_column(ds_filtered, 'Poluente', pollutant)
            
            mean_by_day = obtain_mean_group_of_numerical_column_by_day(ds_filtered, 'Data')
            mean_by_month = obtain_mean_group_of_numerical_column_by_month(ds_filtered, 'Data', 'Valor')

            # NAO ESTÁ SAINDO RESULTADO
            #mean_by_year = obtain_mean_group_of_numerical_column_by_year(ds_filtered, pollutant)
            
            #print('dados', year_dataset, '/',station, '/',pollutant)

            #print(mean_by_month.index)
            #print(mean_by_month.values)


            xlabel_title = 'Mês'
            ylabel_title = 'ug/m3'
            titulo = f'{year_dataset} - {pollutant} - {station}'

            #df = pd.DataFrame(mean_by_month.values, mean_by_month.index)
            #df.plot(title=titulo, xlabel=xlabel_title, ylabel=ylabel_title)
            
#            datas.append(mean_by_month.values, mean_by_month.index)
            
##        df = pd.DataFrame(datas)
#        df.plot(title=titulo, xlabel=xlabel_title, ylabel=ylabel_title)
            
    
#xlabel_title = 'Mês'
#ylabel_title = 'ug/m3'

#df = pd.DataFrame(list(zip(agrupamento_estacao1_ano1_poluente1_mes.values,agrupamento_estacao2_ano1_poluente1_mes.values )),index=agrupamento_estacao2_ano1_poluente1_mes.index, columns=[nome_estacao_1,nome_estacao_2])
#titulo=f"Comparativo mensal entre emissões de {poluente_1} em {nome_estacao_1} e {nome_estacao_2} em {ano1}"
#df.plot(title=titulo, xlabel=xlabel_title, ylabel=ylabel_title)
#df.plot.bar(title=titulo,xlabel=xlabel_title, ylabel=ylabel_title)

In [6]:
dados = {'Estacao': 'Cubatão - Centro', 'Estacao': 'Itaim Paulista' }

for i in dados:
    print(dados.keys())

dict_keys(['Estacao'])